import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "./ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(
        'relative h-full font-sans antialiased',
        inter.className
      )}>
        <Navbar />
        <main className="relative flex flex-col min-h-screen p-4">
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
